development:
  dialect: postgres
  datasource: "dbname=ithub host=db user=postgres password=postgres port=5432 sslmode=disable"
  dir: db/migrations
  table: migrations

production:
  dialect: postgres
  datasource: ${DB_URL}
  dir: db/migrations
  table: migrations
